backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: /assets

collections:
  - label: "Blog"
    name: "blog"
    folder: "src/posts"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Post Author", name: "author", widget: "relation", collection: "authors", searchFields: ["title"], valueField: "title", displayFields: ["title"]}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Type", name: "type", widget: "hidden", default: "blog"}
  - label: "Recipes"
    name: "recipes"
    folder: "src/recipes"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime" required: false}
      - {label: "Featured Image", name: "thumbnail", widget: "image" required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Type", name: "type", widget: "hidden", default: "recipe"}
  - label: "Authors"
    name: "authors"
    folder: "static/admin/authors"
    create: true
    fields:
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Image", name: "authorImage", widget: "image"}
      - {label: "Email", name: "email", widget: "string"}
      - {label: "Quick Bio", name: "quickBio", widget: "string"}

      